package info.shelfunit.james.hibernate.pojos;
// Generated Mar 14, 2010 11:02:37 AM by Hibernate Tools 3.2.1.GA



/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private String username;
     private String pwdHash;
     private String pwdAlgorithm;
     private Short useForwarding;
     private String forwardDestination;
     private Short useAlias;
     private String alias;

    public Users() {
    }

	
    public Users(String username) {
        this.username = username;
    }
    public Users(String username, String pwdHash, String pwdAlgorithm, Short useForwarding, String forwardDestination, Short useAlias, String alias) {
       this.username = username;
       this.pwdHash = pwdHash;
       this.pwdAlgorithm = pwdAlgorithm;
       this.useForwarding = useForwarding;
       this.forwardDestination = forwardDestination;
       this.useAlias = useAlias;
       this.alias = alias;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPwdHash() {
        return this.pwdHash;
    }
    
    public void setPwdHash(String pwdHash) {
        this.pwdHash = pwdHash;
    }
    public String getPwdAlgorithm() {
        return this.pwdAlgorithm;
    }
    
    public void setPwdAlgorithm(String pwdAlgorithm) {
        this.pwdAlgorithm = pwdAlgorithm;
    }
    public Short getUseForwarding() {
        return this.useForwarding;
    }
    
    public void setUseForwarding(Short useForwarding) {
        this.useForwarding = useForwarding;
    }
    public String getForwardDestination() {
        return this.forwardDestination;
    }
    
    public void setForwardDestination(String forwardDestination) {
        this.forwardDestination = forwardDestination;
    }
    public Short getUseAlias() {
        return this.useAlias;
    }
    
    public void setUseAlias(Short useAlias) {
        this.useAlias = useAlias;
    }
    public String getAlias() {
        return this.alias;
    }
    
    public void setAlias(String alias) {
        this.alias = alias;
    }




}


