package org.apache.james.admin.webapp.hibernate.pojos;
// Generated Oct 3, 2011 12:14:31 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users"
    ,catalog="jamesemail"
)
public class Users  implements java.io.Serializable {


     private String username;
     private String pwdHash;
     private String pwdAlgorithm;
     private Short useForwarding;
     private String forwardDestination;
     private Short useAlias;
     private String alias;

    public Users() {
    }

	
    public Users(String username) {
        this.username = username;
    }
    public Users(String username, String pwdHash, String pwdAlgorithm, Short useForwarding, String forwardDestination, Short useAlias, String alias) {
       this.username = username;
       this.pwdHash = pwdHash;
       this.pwdAlgorithm = pwdAlgorithm;
       this.useForwarding = useForwarding;
       this.forwardDestination = forwardDestination;
       this.useAlias = useAlias;
       this.alias = alias;
    }
   
     @Id 
    
    @Column(name="username", unique=true, nullable=false, length=64)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    
    @Column(name="pwdHash", length=100)
    public String getPwdHash() {
        return this.pwdHash;
    }
    
    public void setPwdHash(String pwdHash) {
        this.pwdHash = pwdHash;
    }
    
    @Column(name="pwdAlgorithm", length=20)
    public String getPwdAlgorithm() {
        return this.pwdAlgorithm;
    }
    
    public void setPwdAlgorithm(String pwdAlgorithm) {
        this.pwdAlgorithm = pwdAlgorithm;
    }
    
    @Column(name="useForwarding")
    public Short getUseForwarding() {
        return this.useForwarding;
    }
    
    public void setUseForwarding(Short useForwarding) {
        this.useForwarding = useForwarding;
    }
    
    @Column(name="forwardDestination")
    public String getForwardDestination() {
        return this.forwardDestination;
    }
    
    public void setForwardDestination(String forwardDestination) {
        this.forwardDestination = forwardDestination;
    }
    
    @Column(name="useAlias")
    public Short getUseAlias() {
        return this.useAlias;
    }
    
    public void setUseAlias(Short useAlias) {
        this.useAlias = useAlias;
    }
    
    @Column(name="alias")
    public String getAlias() {
        return this.alias;
    }
    
    public void setAlias(String alias) {
        this.alias = alias;
    }




}


