/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.james.admin.webapp.hibernate.pojos;
// Generated May 9, 2010 2:26:37 PM by Hibernate Tools 3.2.1.GA

/**
 * DeadletterId generated by hbm2java
 */
public class DeadletterId  implements java.io.Serializable {


     private String repositoryName;
     private String messageName;

    public DeadletterId() {
    }

    public DeadletterId(String repositoryName, String messageName) {
       this.repositoryName = repositoryName;
       this.messageName = messageName;
    }
   
    public String getRepositoryName() {
        return this.repositoryName;
    }
    
    public void setRepositoryName(String repositoryName) {
        this.repositoryName = repositoryName;
    }
    public String getMessageName() {
        return this.messageName;
    }
    
    public void setMessageName(String messageName) {
        this.messageName = messageName;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DeadletterId) ) return false;
		 DeadletterId castOther = ( DeadletterId ) other; 
         
		 return ( (this.getRepositoryName()==castOther.getRepositoryName()) || ( this.getRepositoryName()!=null && castOther.getRepositoryName()!=null && this.getRepositoryName().equals(castOther.getRepositoryName()) ) )
 && ( (this.getMessageName()==castOther.getMessageName()) || ( this.getMessageName()!=null && castOther.getMessageName()!=null && this.getMessageName().equals(castOther.getMessageName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getRepositoryName() == null ? 0 : this.getRepositoryName().hashCode() );
         result = 37 * result + ( getMessageName() == null ? 0 : this.getMessageName().hashCode() );
         return result;
   }   


}


