/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.james.admin.webapp.hibernate.pojos;
// Generated May 9, 2010 2:26:37 PM by Hibernate Tools 3.2.1.GA

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private String username;
     private String pwdHash;
     private String pwdAlgorithm;
     private Short useForwarding;
     private String forwardDestination;
     private Short useAlias;
     private String alias;

    public Users() {
    }

	
    public Users(String username) {
        this.username = username;
    }
    public Users(String username, String pwdHash, String pwdAlgorithm, Short useForwarding, String forwardDestination, Short useAlias, String alias) {
       this.username = username;
       this.pwdHash = pwdHash;
       this.pwdAlgorithm = pwdAlgorithm;
       this.useForwarding = useForwarding;
       this.forwardDestination = forwardDestination;
       this.useAlias = useAlias;
       this.alias = alias;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPwdHash() {
        return this.pwdHash;
    }
    
    public void setPwdHash(String pwdHash) {
        this.pwdHash = pwdHash;
    }
    public String getPwdAlgorithm() {
        return this.pwdAlgorithm;
    }
    
    public void setPwdAlgorithm(String pwdAlgorithm) {
        this.pwdAlgorithm = pwdAlgorithm;
    }
    public Short getUseForwarding() {
        return this.useForwarding;
    }
    
    public void setUseForwarding(Short useForwarding) {
        this.useForwarding = useForwarding;
    }
    public String getForwardDestination() {
        return this.forwardDestination;
    }
    
    public void setForwardDestination(String forwardDestination) {
        this.forwardDestination = forwardDestination;
    }
    public Short getUseAlias() {
        return this.useAlias;
    }
    
    public void setUseAlias(Short useAlias) {
        this.useAlias = useAlias;
    }
    public String getAlias() {
        return this.alias;
    }
    
    public void setAlias(String alias) {
        this.alias = alias;
    }




}


